workflows:
  flutter-android:
    name: Flutter Android Build
    instance_type: mac_mini_m1
    max_build_duration: 30
    environment:
      flutter: stable
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
    scripts:
      - flutter pub get
      - flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
